export type CountryType =
  | 'all'
  | 'korea'
  | 'pizza'
  | 'china'
  | 'japan'
  | 'asia'
  | 'mexico'
  | 'italy'
  | 'france';

export type MenuItem = {
  menu: string;
  image: string;
  tags?: string[];
};

export type MenuMap = Record<CountryType, MenuItem[]>;

const IMG = '/img/ahoxy/menu';

const korea: MenuItem[] = [
  { menu: "김밥 꼬마김밥 충무김밥 참치김밥 유부김밥 불고기김밥 제육김밥", image: `${IMG}/gimbap.webp` },
  { menu: "라면 치즈라면 떡라면 참치라면 콩나물라면", image: `${IMG}/ramyun.webp` },
  { menu: "떡볶이 엽기떡볶이", image: `${IMG}/tteokbokki.webp` },
  { menu: "순대 찹쌀순대 오징어순대", image: `${IMG}/sundae.webp` },
  { menu: "족발", image: `${IMG}/jokbal.webp` },
  { menu: "어묵탕 어묵볶음", image: `${IMG}/eomuk.webp`, tags: ["따뜻함", "겨울"] },
  { menu: "떡갈비", image: `${IMG}/ddgb.webp` },
  { menu: "골뱅이무침", image: `${IMG}/golbaengi-muchim.webp` },
  { menu: "순두부찌개 바지락순두부찌개", image: `${IMG}/sdbjg.webp` },
  { menu: "아구찜", image: `${IMG}/agujjim.webp` },
  { menu: "부대찌개", image: `${IMG}/bdjg.webp` },
  { menu: "대게찜", image: `${IMG}/dgj.webp` },
  { menu: "갈비탕", image: `${IMG}/galbitang.webp` },
  { menu: "감자탕", image: `${IMG}/gamjatang.webp` },
  { menu: "낙지볶음 낙지덮밥 낙곱새", image: `${IMG}/ngs.webp` },
  { menu: "닭볶음탕", image: `${IMG}/ddrt.webp` },
  { menu: "묵은지 돼지김치찜", image: `${IMG}/djkcj.webp` },
  { menu: "찜닭 안동찜닭", image: `${IMG}/jjimdak.webp` },
  { menu: "해장국 시래기해장국 뼈해장국", image: `${IMG}/bhjg.webp` },
  { menu: "회 참치회 포항물회 회덮밥", image: `${IMG}/hoe.webp`, tags: ["신선함", "여름"] },
  { menu: "비빔국수 쫄면 열무비빔국수", image: `${IMG}/bibim.webp` },
  { menu: "칼국수 들깨칼국수 닭칼국수 매생이굴칼국수", image: `${IMG}/kgs.webp`, tags: ["따뜻함", "겨울"] },
  { menu: "수제비 들깨수제비 김치수제비", image: `${IMG}/sjb.webp` },
  { menu: "물냉면 평양냉면 밀면", image: `${IMG}/mul-naengmyeon.webp`, tags: ["시원함", "여름"] },
  { menu: "비빔냉면 열무냉면 회냉면", image: `${IMG}/bibim-naengmyeon.webp`, tags: ["시원함", "여름"] },
  { menu: "만둣국", image: `${IMG}/mandu-guk.webp`, tags: ["따뜻함", "겨울"] },
  { menu: "육개장 버섯육개장 소고기육개장", image: `${IMG}/ygj.webp` },
  { menu: "된장찌개 차돌박이된장찌개 청국장", image: `${IMG}/djjg.webp` },
  { menu: "김치찌개 꽁치김치찌개 돼지고기김치찌개", image: `${IMG}/kcjg.webp` },
  { menu: "매운탕 광어매운탕 꽃게매운탕", image: `${IMG}/mt.webp` },
  { menu: "순대국밥 돼지국밥", image: `${IMG}/sundae-gukbap.webp` },
  { menu: "설렁탕", image: `${IMG}/slt.webp` },
  { menu: "알밥", image: `${IMG}/al-bap.webp` },
  { menu: "파전 감자전 해물전", image: `${IMG}/pajeon.webp` },
  { menu: "전복죽 호박죽 소고기죽 해물죽", image: `${IMG}/juk.webp` },
  { menu: "삼계탕 닭한마리", image: `${IMG}/samgyetang.webp`, tags: ["따뜻함", "여름", "보양식"] },
  { menu: "콩나물국밥 콩나물비빔밥", image: `${IMG}/knm.webp` },
  { menu: "장어구이 장어덮밥", image: `${IMG}/jang-eo-gui.webp` },
  { menu: "꽃게탕", image: `${IMG}/ggt.webp`, tags: ["따뜻함", "가을"] },
  { menu: "잔치국수", image: `${IMG}/jcgs.webp` },
  { menu: "육회 육회비빔밥", image: `${IMG}/yookhoe.webp` },
  { menu: "삼겹살 오겹살 갈매기살 항정살", image: `${IMG}/samgyeopsal.webp`, tags: ["고기", "봄"] },
  { menu: "제육볶음 제육쌈밥 제육덮밥", image: `${IMG}/jeyook.jfif` },
  { menu: "닭갈비 불닭 치즈닭갈비", image: `${IMG}/dgb.webp` },
  { menu: "닭꼬치", image: `${IMG}/dkch.webp` },
  { menu: "훈제오리 오리주물럭", image: `${IMG}/hjori.webp` },
  { menu: "갈비찜 LA갈비찜", image: `${IMG}/galbijjim.webp` },
  { menu: "숯불갈비 LA갈비 등갈비", image: `${IMG}/sutbul-galbi.webp` },
  { menu: "뚝배기 불고기", image: `${IMG}/ddb.webp` },
  { menu: "꼬막 꼬막비빔밥", image: `${IMG}/kkm.webp` },
  { menu: "돼지고기 수육 보쌈", image: `${IMG}/suyook.webp` },
  { menu: "홍합탕", image: `${IMG}/honghab.webp` },
  { menu: "떡국", image: `${IMG}/tgtg.webp` },
  { menu: "폭탄 계란찜", image: `${IMG}/grj.webp` },
  { menu: "곰탕 나주곰탕 꼬리곰탕", image: `${IMG}/gomtang.webp` },
  { menu: "호떡", image: `${IMG}/hott.webp` },
  { menu: "잡채", image: `${IMG}/japchae.webp` },
  { menu: "미역국", image: `${IMG}/myg.webp` },
  { menu: "콩국수", image: `${IMG}/cgscgs.webp` },
  { menu: "메밀국수 막국수 들기름막국수", image: `${IMG}/mmgs.webp` },
  { menu: "산낙지", image: `${IMG}/sannak.webp` },
  { menu: "조개구이 가리비구이", image: `${IMG}/jgjgjg.webp` },
  { menu: "고등어구이 삼치구이", image: `${IMG}/mackeee.webp` },
  { menu: "감자조림 알감자조림", image: `${IMG}/gamjajorim.webp` },
  { menu: "소고기무국 무국", image: `${IMG}/moot.webp` },
  { menu: "곱창 곱창전골", image: `${IMG}/gobchang.webp` },
  { menu: "두부조림", image: `${IMG}/dbjr.webp` },
  { menu: "두루치기 돼지두루치기", image: `${IMG}/duru.webp` },
  { menu: "알탕", image: `${IMG}/altang.webp` },
  { menu: "추어탕", image: `${IMG}/choot.webp` },
  { menu: "닭발 닭똥집", image: `${IMG}/dakbb.webp` },
  { menu: "솥밥 스테이크솥밥", image: `${IMG}/sotbap.webp` },
  // Regional specialties
  { menu: "강릉감자옹심이", image: `${IMG}/converted_강릉감자옹심이.webp` },
  { menu: "강릉초당순두부", image: `${IMG}/converted_강릉초당순두부.webp` },
  { menu: "거제대구탕", image: `${IMG}/converted_거제대구탕.webp` },
  { menu: "고성하모회", image: `${IMG}/converted_고성하모회.webp` },
  { menu: "고창풍천장어구이", image: `${IMG}/converted_고창풍천장어구이.webp` },
  { menu: "광양불고기", image: `${IMG}/converted_광양불고기.webp` },
  { menu: "광주송정떡갈비", image: `${IMG}/converted_광주송정떡갈비.webp` },
  { menu: "광주오리탕", image: `${IMG}/converted_광주오리탕.webp` },
  { menu: "나주곰탕", image: `${IMG}/converted_나주곰탕.webp` },
  { menu: "나주영산포홍어", image: `${IMG}/converted_나주영산포홍어.webp` },
  { menu: "남원추어탕", image: `${IMG}/converted_남원추어탕.webp` },
  { menu: "대구납작만두", image: `${IMG}/converted_대구납작만두.webp` },
  { menu: "대구동인동찜갈비", image: `${IMG}/converted_대구동인동찜갈비.webp` },
  { menu: "대구막창", image: `${IMG}/converted_대구막창.webp` },
  { menu: "목포세발낙지", image: `${IMG}/converted_목포세발낙지.webp` },
  { menu: "목포홍어삼합", image: `${IMG}/converted_목포홍어삼합.webp` },
  { menu: "부산돼지국밥", image: `${IMG}/converted_부산돼지국밥.webp` },
  { menu: "부산밀면", image: `${IMG}/converted_부산밀면.webp` },
  { menu: "순천짱뚱어탕", image: `${IMG}/converted_순천짱뚱어탕.webp` },
  { menu: "안동간고등어정식", image: `${IMG}/converted_안동간고등어정식.webp` },
  { menu: "여수금풍생이구이", image: `${IMG}/converted_여수금풍생이구이.webp` },
  { menu: "여수돌게장", image: `${IMG}/converted_여수돌게장.webp` },
  { menu: "여수서대회", image: `${IMG}/converted_여수서대회.webp` },
  { menu: "영광법성포굴비정식", image: `${IMG}/converted_영광법성포굴비정식.webp` },
  { menu: "영덕대게찜", image: `${IMG}/converted_영덕대게찜.webp` },
  { menu: "전주콩나물국밥", image: `${IMG}/converted_전주콩나물국밥.webp` },
  { menu: "진주냉면", image: `${IMG}/converted_진주냉면.webp` },
  { menu: "진주비빔밥", image: `${IMG}/converted_진주비빔밥.webp` },
  { menu: "창원아구찜", image: `${IMG}/converted_창원아구찜.webp` },
  { menu: "춘천닭갈비", image: `${IMG}/converted_춘천닭갈비.webp` },
  { menu: "통영충무김밥", image: `${IMG}/converted_통영충무김밥.webp` },
  { menu: "포항물회", image: `${IMG}/converted_포항물회.webp` },
  { menu: "보성벌교꼬막정식", image: `${IMG}/converted_보성벌교꼬막정식.webp` },
  { menu: "장흥삼합", image: `${IMG}/converted_장흥삼합.webp` },
  { menu: "담양창평국밥", image: `${IMG}/converted_담양창평국밥.webp` },
  { menu: "양양섭국", image: `${IMG}/converted_양양섭국.webp` },
  { menu: "화순순두부", image: `${IMG}/converted_화순순두부.webp` },
  { menu: "보성양탕", image: `${IMG}/converted_보성양탕.webp` },
];

const pizza: MenuItem[] = [
  { menu: "피자 고르곤졸라피자 마르게리타 시카고피자", image: `${IMG}/pizza.webp` },
  { menu: "치킨", image: `${IMG}/chicken.webp` },
  { menu: "햄버거", image: `${IMG}/hamburger.webp` },
  { menu: "팬케이크", image: `${IMG}/pancake.webp` },
  { menu: "와플", image: `${IMG}/waffle.webp` },
  { menu: "샌드위치", image: `${IMG}/sandwich.webp` },
  { menu: "핫도그 명랑핫도그 콘도그", image: `${IMG}/hot-dog.webp` },
  { menu: "토스트", image: `${IMG}/toast.webp` },
  { menu: "치즈스틱", image: `${IMG}/cheese-sticks.webp` },
  { menu: "붕어빵", image: `${IMG}/bb.webp` },
  { menu: "닭강정", image: `${IMG}/dakgangjeong.webp` },
  { menu: "스테이크", image: `${IMG}/steak.webp` },
  { menu: "폭립 Pork Rib", image: `${IMG}/porkrib.webp` },
  { menu: "연어 스테이크", image: `${IMG}/salmonsteak.webp` },
  { menu: "연어 샐러드 훈제연어", image: `${IMG}/salmon.webp` },
  { menu: "당근 케이크", image: `${IMG}/carrotcake.webp` },
  { menu: "오믈렛", image: `${IMG}/omelette.webp` },
  { menu: "도넛", image: `${IMG}/donut.webp` },
  { menu: "프레첼", image: `${IMG}/pretzel.webp` },
  { menu: "포케 연어포케", image: `${IMG}/poke.webp` },
];

const china: MenuItem[] = [
  { menu: "짜장면 짬뽕 삼선짜장", image: `${IMG}/jjajangmyun.webp` },
  { menu: "탕수육", image: `${IMG}/tangsuyook.webp` },
  { menu: "마라탕", image: `${IMG}/malatang.jfif` },
  { menu: "마라샹궈", image: `${IMG}/mlsg.webp` },
  { menu: "고추잡채", image: `${IMG}/gcj.webp` },
  { menu: "깐풍기", image: `${IMG}/kpg.jfif` },
  { menu: "딤섬", image: `${IMG}/dim-sum.webp` },
  { menu: "팔보채", image: `${IMG}/pbc.webp` },
  { menu: "꿔바로우", image: `${IMG}/gbr.webp` },
  { menu: "마파두부", image: `${IMG}/mafatofu.webp` },
  { menu: "훠궈 샤브샤브 핫팟", image: `${IMG}/shabu.webp` },
  { menu: "북경오리 베이징덕", image: `${IMG}/pekingduck.webp` },
  { menu: "샤오롱바오", image: `${IMG}/xiaolong.webp` },
];

const japan: MenuItem[] = [
  { menu: "라멘", image: `${IMG}/ramen.webp` },
  { menu: "덴뿌라", image: `${IMG}/tempura.webp` },
  { menu: "스시 초밥", image: `${IMG}/sushi.webp` },
  { menu: "돈카츠 경양식돈까스", image: `${IMG}/tonkatsu.webp` },
  { menu: "야끼도리", image: `${IMG}/yakitori.webp` },
  { menu: "우동 가케우동", image: `${IMG}/udon.webp` },
  { menu: "오코노미야키", image: `${IMG}/okonomiyaki.webp` },
  { menu: "타코야키", image: `${IMG}/takoyaki.webp` },
  { menu: "치라시스시 치라시볼", image: `${IMG}/chirashi.webp` },
  { menu: "스키야키", image: `${IMG}/sukiyaki.webp` },
  { menu: "돈부리", image: `${IMG}/donburi.webp` },
  { menu: "소바", image: `${IMG}/soba.webp` },
  { menu: "오야코동", image: `${IMG}/oyakodon.webp` },
  { menu: "오차즈케 녹차밥", image: `${IMG}/och.webp` },
];

const asia: MenuItem[] = [
  { menu: "쌀국수 Pho", image: `${IMG}/pho.webp` },
  { menu: "분짜", image: `${IMG}/bunjja.webp` },
  { menu: "팟타이", image: `${IMG}/pod.webp` },
  { menu: "반미샌드위치", image: `${IMG}/banhmi.webp` },
  { menu: "쏨땀 태국샐러드", image: `${IMG}/somtam.webp` },
  { menu: "망고 찹쌀밥", image: `${IMG}/mango.webp` },
  { menu: "나시고랭", image: `${IMG}/nasi-goreng.webp` },
  { menu: "인도 커리 & 난", image: `${IMG}/indiancurry.webp` },
  { menu: "탄두리 치킨", image: `${IMG}/tanduri.webp` },
  { menu: "양꼬치", image: `${IMG}/yangkkochi.webp` },
  { menu: "똠양꿍", image: `${IMG}/tygtyg.webp` },
  { menu: "월남쌈 베트남 스프링롤", image: `${IMG}/vietssam.webp` },
];

const mexico: MenuItem[] = [
  { menu: "타코", image: `${IMG}/tacos.webp` },
  { menu: "엔칠라다", image: `${IMG}/enchiladas.webp` },
  { menu: "케사디아", image: `${IMG}/quesadilla.webp` },
  { menu: "감바스 알 아히요", image: `${IMG}/gambas.webp` },
  { menu: "타말레스", image: `${IMG}/tamales.webp` },
  { menu: "포졸레", image: `${IMG}/pozole.webp` },
  { menu: "파히타", image: `${IMG}/fajitas.webp` },
  { menu: "과카몰리", image: `${IMG}/guacamole.webp` },
  { menu: "빠에야 Paella", image: `${IMG}/paella.webp` },
  { menu: "가스파초 Gazpacho", image: `${IMG}/gazpacho.webp` },
  { menu: "타파스 Tapas", image: `${IMG}/tapas.webp` },
  { menu: "세비체 Ceviche", image: `${IMG}/ceviche.webp` },
];

const italy: MenuItem[] = [
  { menu: "라자냐", image: `${IMG}/lasagna.webp` },
  { menu: "카프레제", image: `${IMG}/caprese.webp` },
  { menu: "젤라또", image: `${IMG}/gelato.webp` },
  { menu: "파스타 알리오올리오 봉골레 까르보나라 볼로네제 크림", image: `${IMG}/pasta.webp` },
  { menu: "마르게리따 피자", image: `${IMG}/margherita-pizza.webp` },
  { menu: "리조또", image: `${IMG}/risotto.webp` },
  { menu: "브루스케타", image: `${IMG}/bruschetta.webp` },
  { menu: "티라미수", image: `${IMG}/tiramisu.webp` },
  { menu: "파니니", image: `${IMG}/panini.webp` },
  { menu: "라비올리", image: `${IMG}/lavioli.webp` },
];

const france: MenuItem[] = [
  { menu: "크로크무슈", image: `${IMG}/croque.webp` },
  { menu: "키쉬 로레인", image: `${IMG}/quiche.webp` },
  { menu: "니수아즈 샐러드", image: `${IMG}/salade.webp` },
  { menu: "라따뚜이", image: `${IMG}/ratatouille.webp` },
  { menu: "부야베스 해물스튜", image: `${IMG}/bouillabaisse.webp` },
  { menu: "스테이크 감자프라이", image: `${IMG}/steak-frites.webp` },
  { menu: "타르트 태탕 사과파이", image: `${IMG}/tarte-tatin.webp` },
  { menu: "크레페", image: `${IMG}/crepe.webp` },
  { menu: "그라탕", image: `${IMG}/gratin.webp` },
  { menu: "에스까르고", image: `${IMG}/escargot.webp` },
  { menu: "포아그라", image: `${IMG}/foie-Gras.webp` },
  { menu: "마카롱", image: `${IMG}/macaron.webp` },
  { menu: "양파 수프", image: `${IMG}/onionsoup.webp` },
  { menu: "클레멘타인 크럼블", image: `${IMG}/clementine.webp` },
  { menu: "레몬 타르트", image: `${IMG}/tartecit.webp` },
];

const menuData: MenuMap = {
  all: [...korea, ...pizza, ...china, ...japan, ...asia, ...mexico, ...italy, ...france],
  korea,
  pizza,
  china,
  japan,
  asia,
  mexico,
  italy,
  france,
};

export default menuData;

export const countryLabels: Record<CountryType, string> = {
  all: '🌍 전체',
  korea: '🇰🇷 한식',
  pizza: '🍕 피자/치킨/양식',
  china: '🇨🇳 중식',
  japan: '🇯🇵 일식',
  asia: '🌏 아시안',
  mexico: '🇲🇽 스페인/멕시코',
  italy: '🇮🇹 이탈리아',
  france: '🇫🇷 프랑스',
};
